language: python

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

script:
  - tox

env:
  - TOXENV=django17-py27
  - TOXENV=django17-py34
  - TOXENV=django18-py27
  - TOXENV=django18-py33
  - TOXENV=django18-py34
  - TOXENV=django18-pypy
  - TOXENV=django19-py27
  - TOXENV=django19-py34
  - TOXENV=django19-pypy

after_success:
  - coveralls