language: python

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

script:
  - tox

env:
  - TOXENV=django14-py26
  - TOXENV=django14-py27
  - TOXENV=django14-pypy
  - TOXENV=django15-py26
  - TOXENV=django15-py27
  - TOXENV=django15-py32
  - TOXENV=django15-py33
  - TOXENV=django15-py34
  - TOXENV=django15-pypy
  - TOXENV=django16-py26
  - TOXENV=django16-py27
  - TOXENV=django16-py32
  - TOXENV=django16-py33
  - TOXENV=django16-py34
  - TOXENV=django16-pypy
  - TOXENV=django17-py27
  - TOXENV=django17-py32
  - TOXENV=django17-py33
  - TOXENV=django17-py34
  - TOXENV=django17-pypy
  - TOXENV=django18-py27
  - TOXENV=django18-py32
  - TOXENV=django18-py33
  - TOXENV=django18-py34
  - TOXENV=django18-pypy

after_success:
  - coveralls